=begin
#shotstack

#The Shotstack API is a video editing service that allows for the programatic creation of videos using JSON. 

OpenAPI spec version: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.0-beta3

=end

module Shotstack
  VERSION = "0.0.10"
end
