# -*- encoding: utf-8 -*-

=begin
#Shotstack

# Official Ruby SDK for the Shotstack Cloud Video Editing API

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.4.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "shotstack/version"

Gem::Specification.new do |s|
  s.name        = "shotstack"
  s.version     = Shotstack::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Shotstack"]
  s.email       = ["ruby@shotstack.io"]
  s.homepage    = "https://shotstack.io/product/sdk/ruby/"
  s.summary     = "Shotstack Ruby Gem"
  s.description = "Official Ruby SDK for the Shotstack Cloud Video Editing API"
  s.license     = "MIT"
  s.required_ruby_version = ">= 2.7"
  s.metadata    = {}

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.executables   = []
  s.require_paths = ["lib"]
end
