=begin
#Shotstack

#The Shotstack API is a video editing service that allows for the automated creation of videos using JSON. You can configure an edit and POST it to the Shotstack API which will render your video and provide a file location when complete. For more details check https://shotstack.io

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.1

=end

# Common files
require 'shotstack/api_client'
require 'shotstack/api_error'
require 'shotstack/version'
require 'shotstack/configuration'

# Models
require 'shotstack/models/audio_asset'
require 'shotstack/models/clip'
require 'shotstack/models/edit'
require 'shotstack/models/font'
require 'shotstack/models/html_asset'
require 'shotstack/models/image_asset'
require 'shotstack/models/luma_asset'
require 'shotstack/models/offset'
require 'shotstack/models/output'
require 'shotstack/models/poster'
require 'shotstack/models/queued_response'
require 'shotstack/models/queued_response_data'
require 'shotstack/models/render_response'
require 'shotstack/models/render_response_data'
require 'shotstack/models/soundtrack'
require 'shotstack/models/thumbnail'
require 'shotstack/models/timeline'
require 'shotstack/models/title_asset'
require 'shotstack/models/track'
require 'shotstack/models/transition'
require 'shotstack/models/video_asset'

# APIs
require 'shotstack/api/endpoints_api'

module Shotstack
  class << self
    # Customize default settings for the SDK using block.
    #   Shotstack.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
