=begin
#Shotstack

# Official Ruby SDK for the Shotstack Cloud Video Editing API

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.4.0

=end

require 'date'
require 'time'

module Shotstack
  # The type of asset to display for the duration of the Clip, i.e. a video clip or an image. Choose from one of the available asset types below.
  module Asset
    class << self
      # List of class defined in oneOf (OpenAPI v3)
      def openapi_one_of
        [
          :'AudioAsset',
          :'CaptionAsset',
          :'Html5Asset',
          :'HtmlAsset',
          :'ImageAsset',
          :'ImageToVideoAsset',
          :'LumaAsset',
          :'RichCaptionAsset',
          :'RichTextAsset',
          :'ShapeAsset',
          :'SvgAsset',
          :'TextAsset',
          :'TextToImageAsset',
          :'TextToSpeechAsset',
          :'TitleAsset',
          :'VideoAsset'
        ]
      end

      # Discriminator's property name (OpenAPI v3)
      def openapi_discriminator_name
        :'type'
      end

      # Discriminator's mapping (OpenAPI v3)
      def openapi_discriminator_mapping
        {
          :'audio' => :'AudioAsset',
          :'caption' => :'CaptionAsset',
          :'html' => :'HtmlAsset',
          :'html5' => :'Html5Asset',
          :'image' => :'ImageAsset',
          :'image-to-video' => :'ImageToVideoAsset',
          :'luma' => :'LumaAsset',
          :'rich-caption' => :'RichCaptionAsset',
          :'rich-text' => :'RichTextAsset',
          :'shape' => :'ShapeAsset',
          :'svg' => :'SvgAsset',
          :'text' => :'TextAsset',
          :'text-to-image' => :'TextToImageAsset',
          :'text-to-speech' => :'TextToSpeechAsset',
          :'title' => :'TitleAsset',
          :'video' => :'VideoAsset'
        }
      end

      # Builds the object
      # @param [Mixed] Data to be matched against the list of oneOf items
      # @return [Object] Returns the model or the data itself
      def build(data)
        discriminator_value = data[openapi_discriminator_name]
        return nil if discriminator_value.nil?

        klass = openapi_discriminator_mapping[discriminator_value.to_s.to_sym]
        return nil unless klass

        Shotstack.const_get(klass).build_from_hash(data)
      end
    end
  end

end
