=begin
#Shotstack

# Official Ruby SDK for the Shotstack Cloud Video Editing API

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.4.0

=end

require 'date'
require 'time'

module Shotstack
  # Background styling properties for the text bounding box.
  class RichTextBackground
    # The background color using hexadecimal color notation.
    attr_accessor :color

    # The opacity of the background where 1 is opaque and 0 is transparent.
    attr_accessor :opacity

    # The border radius of the background box in pixels. Must be 0 or greater.
    attr_accessor :border_radius

    # When true, the background pill shrinks to fit the rendered text bounding box plus the asset's padding (and stroke width, if present), producing a pill or badge effect. When false (default), the background fills the full asset content area. Available on rich-text and rich-caption assets only; not supported on legacy `type: text`. 
    attr_accessor :wrap

    # Inner padding in pixels between the wrap pill edge and the rendered text. Only takes effect when `wrap: true`. When omitted, the renderer applies a sensible default proportional to the font size (approximately 12% of the active page font size on rich-caption assets). Set to 0 for a pill that hugs the text exactly. Available on rich-text and rich-caption assets only. 
    attr_accessor :padding

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'color' => :'color',
        :'opacity' => :'opacity',
        :'border_radius' => :'borderRadius',
        :'wrap' => :'wrap',
        :'padding' => :'padding'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'color' => :'String',
        :'opacity' => :'Float',
        :'border_radius' => :'Float',
        :'wrap' => :'Boolean',
        :'padding' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Shotstack::RichTextBackground` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Shotstack::RichTextBackground`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'color')
        self.color = attributes[:'color']
      end

      if attributes.key?(:'opacity')
        self.opacity = attributes[:'opacity']
      else
        self.opacity = 1
      end

      if attributes.key?(:'border_radius')
        self.border_radius = attributes[:'border_radius']
      else
        self.border_radius = 0
      end

      if attributes.key?(:'wrap')
        self.wrap = attributes[:'wrap']
      else
        self.wrap = false
      end

      if attributes.key?(:'padding')
        self.padding = attributes[:'padding']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      pattern = Regexp.new(/^#[A-Fa-f0-9]{6}$/)
      if !@color.nil? && @color !~ pattern
        invalid_properties.push("invalid value for \"color\", must conform to the pattern #{pattern}.")
      end

      if !@opacity.nil? && @opacity > 1
        invalid_properties.push('invalid value for "opacity", must be smaller than or equal to 1.')
      end

      if !@opacity.nil? && @opacity < 0
        invalid_properties.push('invalid value for "opacity", must be greater than or equal to 0.')
      end

      if !@border_radius.nil? && @border_radius < 0
        invalid_properties.push('invalid value for "border_radius", must be greater than or equal to 0.')
      end

      if !@padding.nil? && @padding > 200
        invalid_properties.push('invalid value for "padding", must be smaller than or equal to 200.')
      end

      if !@padding.nil? && @padding < 0
        invalid_properties.push('invalid value for "padding", must be greater than or equal to 0.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@color.nil? && @color !~ Regexp.new(/^#[A-Fa-f0-9]{6}$/)
      return false if !@opacity.nil? && @opacity > 1
      return false if !@opacity.nil? && @opacity < 0
      return false if !@border_radius.nil? && @border_radius < 0
      return false if !@padding.nil? && @padding > 200
      return false if !@padding.nil? && @padding < 0
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] color Value to be assigned
    def color=(color)
      if color.nil?
        fail ArgumentError, 'color cannot be nil'
      end

      pattern = Regexp.new(/^#[A-Fa-f0-9]{6}$/)
      if color !~ pattern
        fail ArgumentError, "invalid value for \"color\", must conform to the pattern #{pattern}."
      end

      @color = color
    end

    # Custom attribute writer method with validation
    # @param [Object] opacity Value to be assigned
    def opacity=(opacity)
      if opacity.nil?
        fail ArgumentError, 'opacity cannot be nil'
      end

      if opacity > 1
        fail ArgumentError, 'invalid value for "opacity", must be smaller than or equal to 1.'
      end

      if opacity < 0
        fail ArgumentError, 'invalid value for "opacity", must be greater than or equal to 0.'
      end

      @opacity = opacity
    end

    # Custom attribute writer method with validation
    # @param [Object] border_radius Value to be assigned
    def border_radius=(border_radius)
      if border_radius.nil?
        fail ArgumentError, 'border_radius cannot be nil'
      end

      if border_radius < 0
        fail ArgumentError, 'invalid value for "border_radius", must be greater than or equal to 0.'
      end

      @border_radius = border_radius
    end

    # Custom attribute writer method with validation
    # @param [Object] padding Value to be assigned
    def padding=(padding)
      if padding.nil?
        fail ArgumentError, 'padding cannot be nil'
      end

      if padding > 200
        fail ArgumentError, 'invalid value for "padding", must be smaller than or equal to 200.'
      end

      if padding < 0
        fail ArgumentError, 'invalid value for "padding", must be greater than or equal to 0.'
      end

      @padding = padding
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          color == o.color &&
          opacity == o.opacity &&
          border_radius == o.border_radius &&
          wrap == o.wrap &&
          padding == o.padding
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [color, opacity, border_radius, wrap, padding].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Shotstack.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
