=begin
#Shotstack

# Official Ruby SDK for the Shotstack Cloud Video Editing API

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.4.0

=end

require 'date'
require 'time'

module Shotstack
  # Font properties for rich text.
  class RichTextFont
    # The font family name. This must be the Family name embedded in the font, i.e. \"Open Sans\".
    attr_accessor :family

    # The size of the font in pixels (px). Must be between 1 and 500.
    attr_accessor :size

    # The weight of the font. Can be a number (100-900) or a string ('normal', 'bold', etc.). 100 is lightest, 900 is heaviest (boldest).
    attr_accessor :weight

    # The font style.
    attr_accessor :style

    # The text color using hexadecimal color notation.
    attr_accessor :color

    # The opacity of the text where 1 is opaque and 0 is transparent.
    attr_accessor :opacity

    # The background color behind the text using hexadecimal color notation.
    attr_accessor :background

    attr_accessor :stroke

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'family' => :'family',
        :'size' => :'size',
        :'weight' => :'weight',
        :'style' => :'style',
        :'color' => :'color',
        :'opacity' => :'opacity',
        :'background' => :'background',
        :'stroke' => :'stroke'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'family' => :'String',
        :'size' => :'Integer',
        :'weight' => :'Object',
        :'style' => :'String',
        :'color' => :'String',
        :'opacity' => :'Float',
        :'background' => :'String',
        :'stroke' => :'RichTextStroke'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'weight',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Shotstack::RichTextFont` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Shotstack::RichTextFont`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'family')
        self.family = attributes[:'family']
      else
        self.family = 'Open Sans'
      end

      if attributes.key?(:'size')
        self.size = attributes[:'size']
      else
        self.size = 24
      end

      if attributes.key?(:'weight')
        self.weight = attributes[:'weight']
      end

      if attributes.key?(:'style')
        self.style = attributes[:'style']
      else
        self.style = 'normal'
      end

      if attributes.key?(:'color')
        self.color = attributes[:'color']
      else
        self.color = '#000000'
      end

      if attributes.key?(:'opacity')
        self.opacity = attributes[:'opacity']
      else
        self.opacity = 1
      end

      if attributes.key?(:'background')
        self.background = attributes[:'background']
      end

      if attributes.key?(:'stroke')
        self.stroke = attributes[:'stroke']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@size.nil? && @size > 500
        invalid_properties.push('invalid value for "size", must be smaller than or equal to 500.')
      end

      if !@size.nil? && @size < 1
        invalid_properties.push('invalid value for "size", must be greater than or equal to 1.')
      end

      pattern = Regexp.new(/^#[A-Fa-f0-9]{6}$/)
      if !@color.nil? && @color !~ pattern
        invalid_properties.push("invalid value for \"color\", must conform to the pattern #{pattern}.")
      end

      if !@opacity.nil? && @opacity > 1
        invalid_properties.push('invalid value for "opacity", must be smaller than or equal to 1.')
      end

      if !@opacity.nil? && @opacity < 0
        invalid_properties.push('invalid value for "opacity", must be greater than or equal to 0.')
      end

      pattern = Regexp.new(/^#[A-Fa-f0-9]{6}$/)
      if !@background.nil? && @background !~ pattern
        invalid_properties.push("invalid value for \"background\", must conform to the pattern #{pattern}.")
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@size.nil? && @size > 500
      return false if !@size.nil? && @size < 1
      style_validator = EnumAttributeValidator.new('String', ["normal", "italic"])
      return false unless style_validator.valid?(@style)
      return false if !@color.nil? && @color !~ Regexp.new(/^#[A-Fa-f0-9]{6}$/)
      return false if !@opacity.nil? && @opacity > 1
      return false if !@opacity.nil? && @opacity < 0
      return false if !@background.nil? && @background !~ Regexp.new(/^#[A-Fa-f0-9]{6}$/)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] size Value to be assigned
    def size=(size)
      if size.nil?
        fail ArgumentError, 'size cannot be nil'
      end

      if size > 500
        fail ArgumentError, 'invalid value for "size", must be smaller than or equal to 500.'
      end

      if size < 1
        fail ArgumentError, 'invalid value for "size", must be greater than or equal to 1.'
      end

      @size = size
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] style Object to be assigned
    def style=(style)
      validator = EnumAttributeValidator.new('String', ["normal", "italic"])
      unless validator.valid?(style)
        fail ArgumentError, "invalid value for \"style\", must be one of #{validator.allowable_values}."
      end
      @style = style
    end

    # Custom attribute writer method with validation
    # @param [Object] color Value to be assigned
    def color=(color)
      if color.nil?
        fail ArgumentError, 'color cannot be nil'
      end

      pattern = Regexp.new(/^#[A-Fa-f0-9]{6}$/)
      if color !~ pattern
        fail ArgumentError, "invalid value for \"color\", must conform to the pattern #{pattern}."
      end

      @color = color
    end

    # Custom attribute writer method with validation
    # @param [Object] opacity Value to be assigned
    def opacity=(opacity)
      if opacity.nil?
        fail ArgumentError, 'opacity cannot be nil'
      end

      if opacity > 1
        fail ArgumentError, 'invalid value for "opacity", must be smaller than or equal to 1.'
      end

      if opacity < 0
        fail ArgumentError, 'invalid value for "opacity", must be greater than or equal to 0.'
      end

      @opacity = opacity
    end

    # Custom attribute writer method with validation
    # @param [Object] background Value to be assigned
    def background=(background)
      if background.nil?
        fail ArgumentError, 'background cannot be nil'
      end

      pattern = Regexp.new(/^#[A-Fa-f0-9]{6}$/)
      if background !~ pattern
        fail ArgumentError, "invalid value for \"background\", must conform to the pattern #{pattern}."
      end

      @background = background
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          family == o.family &&
          size == o.size &&
          weight == o.weight &&
          style == o.style &&
          color == o.color &&
          opacity == o.opacity &&
          background == o.background &&
          stroke == o.stroke
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [family, size, weight, style, color, opacity, background, stroke].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Shotstack.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
