=begin
#Shotstack

# Official Ruby SDK for the Shotstack Cloud Video Editing API

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.4.0

=end

require 'date'
require 'time'

module Shotstack
  # Text style properties including spacing, line height, and transformations.
  class RichCaptionAssetStyle
    # Additional spacing between letters in pixels. Can be negative for tighter spacing.
    attr_accessor :letter_spacing

    # The line height as a multiplier of the font size. Must be between 0 and 10.
    attr_accessor :line_height

    # Text transformation to apply.
    attr_accessor :text_transform

    # The font size in pixels. Can be used as an alternative to font.size.
    attr_accessor :size

    # Text decoration to apply.
    attr_accessor :text_decoration

    attr_accessor :gradient

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'letter_spacing' => :'letterSpacing',
        :'line_height' => :'lineHeight',
        :'text_transform' => :'textTransform',
        :'size' => :'size',
        :'text_decoration' => :'textDecoration',
        :'gradient' => :'gradient'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'letter_spacing' => :'Float',
        :'line_height' => :'Float',
        :'text_transform' => :'String',
        :'size' => :'Float',
        :'text_decoration' => :'String',
        :'gradient' => :'RichTextGradient'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Shotstack::RichCaptionAssetStyle` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Shotstack::RichCaptionAssetStyle`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'letter_spacing')
        self.letter_spacing = attributes[:'letter_spacing']
      else
        self.letter_spacing = 0
      end

      if attributes.key?(:'line_height')
        self.line_height = attributes[:'line_height']
      else
        self.line_height = 1.2
      end

      if attributes.key?(:'text_transform')
        self.text_transform = attributes[:'text_transform']
      else
        self.text_transform = 'none'
      end

      if attributes.key?(:'size')
        self.size = attributes[:'size']
      end

      if attributes.key?(:'text_decoration')
        self.text_decoration = attributes[:'text_decoration']
      else
        self.text_decoration = 'none'
      end

      if attributes.key?(:'gradient')
        self.gradient = attributes[:'gradient']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@line_height.nil? && @line_height > 10
        invalid_properties.push('invalid value for "line_height", must be smaller than or equal to 10.')
      end

      if !@line_height.nil? && @line_height < 0
        invalid_properties.push('invalid value for "line_height", must be greater than or equal to 0.')
      end

      if !@size.nil? && @size > 500
        invalid_properties.push('invalid value for "size", must be smaller than or equal to 500.')
      end

      if !@size.nil? && @size < 1
        invalid_properties.push('invalid value for "size", must be greater than or equal to 1.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@line_height.nil? && @line_height > 10
      return false if !@line_height.nil? && @line_height < 0
      text_transform_validator = EnumAttributeValidator.new('String', ["none", "uppercase", "lowercase", "capitalize"])
      return false unless text_transform_validator.valid?(@text_transform)
      return false if !@size.nil? && @size > 500
      return false if !@size.nil? && @size < 1
      text_decoration_validator = EnumAttributeValidator.new('String', ["none", "underline", "line-through"])
      return false unless text_decoration_validator.valid?(@text_decoration)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] line_height Value to be assigned
    def line_height=(line_height)
      if line_height.nil?
        fail ArgumentError, 'line_height cannot be nil'
      end

      if line_height > 10
        fail ArgumentError, 'invalid value for "line_height", must be smaller than or equal to 10.'
      end

      if line_height < 0
        fail ArgumentError, 'invalid value for "line_height", must be greater than or equal to 0.'
      end

      @line_height = line_height
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] text_transform Object to be assigned
    def text_transform=(text_transform)
      validator = EnumAttributeValidator.new('String', ["none", "uppercase", "lowercase", "capitalize"])
      unless validator.valid?(text_transform)
        fail ArgumentError, "invalid value for \"text_transform\", must be one of #{validator.allowable_values}."
      end
      @text_transform = text_transform
    end

    # Custom attribute writer method with validation
    # @param [Object] size Value to be assigned
    def size=(size)
      if size.nil?
        fail ArgumentError, 'size cannot be nil'
      end

      if size > 500
        fail ArgumentError, 'invalid value for "size", must be smaller than or equal to 500.'
      end

      if size < 1
        fail ArgumentError, 'invalid value for "size", must be greater than or equal to 1.'
      end

      @size = size
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] text_decoration Object to be assigned
    def text_decoration=(text_decoration)
      validator = EnumAttributeValidator.new('String', ["none", "underline", "line-through"])
      unless validator.valid?(text_decoration)
        fail ArgumentError, "invalid value for \"text_decoration\", must be one of #{validator.allowable_values}."
      end
      @text_decoration = text_decoration
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          letter_spacing == o.letter_spacing &&
          line_height == o.line_height &&
          text_transform == o.text_transform &&
          size == o.size &&
          text_decoration == o.text_decoration &&
          gradient == o.gradient
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [letter_spacing, line_height, text_transform, size, text_decoration, gradient].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Shotstack.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
