=begin
#Shotstack

# Official Ruby SDK for the Shotstack Cloud Video Editing API

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.4.0

=end

require 'date'
require 'time'

module Shotstack
  # The VideoAsset adds a video to a Clip. The video can be sourced from a URL (`src`) or generated from a text prompt (`prompt`), optionally from a starting image (`inputSrc`). Exactly one of `src` or `prompt` must be provided.  - **Source URL:** set `src` to the URL of an mp4 (or compatible) video file. - **Generated:** set `prompt` to describe the motion. Optionally set `inputSrc`   to a starting image URL (image-to-video). Use `model` to choose the generator   (e.g. `luma-ray-3`, `runpod-itv-mini`). The generated `src` is filled in   automatically. 
  class VideoAsset
    # The type of asset - set to `video` for videos.
    attr_accessor :type

    # The video source URL. The URL must be publicly accessible or include credentials. Provide either `src` or `prompt`, not both.
    attr_accessor :src

    # A text prompt to generate the video from. When set without `src`, the engine generates a video and fills `src` automatically. Optionally pair with `inputSrc` for image-to-video. Use `model` to choose the generator.
    attr_accessor :prompt

    # Input image URL for image-to-video generation. The image is used as the starting frame; `prompt` describes the motion. Has no effect unless `prompt` is set.
    attr_accessor :input_src

    # **Deprecated — use `inputSrc`.** Legacy alias for the image-to-video input image URL, accepted and normalised to `inputSrc` on ingest. The name is misleading — industry-wide `seed` means an integer RNG sampling seed — and will be removed in a future major version.
    attr_accessor :seed

    # The generation model to use when `prompt` is set (e.g. `luma-ray-3`, `runpod-itv-mini`). Defaults to the platform's preferred generator if omitted.
    attr_accessor :model

    # Set to `true` to force re-encoding of the video during preprocessing. This can help resolve compatibility issues, fix rotation problems, synchronize audio, or convert formats. The video will be processed to ensure optimal compatibility with the rendering engine.
    attr_accessor :transcode

    # The start trim point of the video clip, in seconds (defaults to 0). Videos will start from the in trim point. The video will play until the file ends or the Clip length is reached.
    attr_accessor :trim

    attr_accessor :volume

    # Preset volume effects to apply to the video asset <ul>   <li>`fadeIn` - fade volume in only</li>   <li>`fadeOut` - fade volume out only</li>   <li>`fadeInFadeOut` - fade volume in and out</li> </ul>
    attr_accessor :volume_effect

    # Adjust the playback speed of the video clip between 0 (paused) and 10 (10x normal speed) where 1 is normal speed (defaults to 1). Adjusting the speed will also adjust the duration of the clip and may require you to adjust the Clip length. For example, if you set speed to 0.5, the clip will need to be 2x as long to play the entire video (i.e. original length / 0.5). If you set speed to 2, the clip will need to be half as long to play the entire video (i.e. original length / 2).
    attr_accessor :speed

    attr_accessor :crop

    attr_accessor :chroma_key

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'type' => :'type',
        :'src' => :'src',
        :'prompt' => :'prompt',
        :'input_src' => :'inputSrc',
        :'seed' => :'seed',
        :'model' => :'model',
        :'transcode' => :'transcode',
        :'trim' => :'trim',
        :'volume' => :'volume',
        :'volume_effect' => :'volumeEffect',
        :'speed' => :'speed',
        :'crop' => :'crop',
        :'chroma_key' => :'chromaKey'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'type' => :'String',
        :'src' => :'String',
        :'prompt' => :'String',
        :'input_src' => :'String',
        :'seed' => :'String',
        :'model' => :'String',
        :'transcode' => :'Boolean',
        :'trim' => :'Float',
        :'volume' => :'VideoAssetVolume',
        :'volume_effect' => :'String',
        :'speed' => :'Float',
        :'crop' => :'Crop',
        :'chroma_key' => :'ChromaKey'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Shotstack::VideoAsset` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Shotstack::VideoAsset`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      else
        self.type = 'video'
      end

      if attributes.key?(:'src')
        self.src = attributes[:'src']
      end

      if attributes.key?(:'prompt')
        self.prompt = attributes[:'prompt']
      end

      if attributes.key?(:'input_src')
        self.input_src = attributes[:'input_src']
      end

      if attributes.key?(:'seed')
        self.seed = attributes[:'seed']
      end

      if attributes.key?(:'model')
        self.model = attributes[:'model']
      end

      if attributes.key?(:'transcode')
        self.transcode = attributes[:'transcode']
      end

      if attributes.key?(:'trim')
        self.trim = attributes[:'trim']
      end

      if attributes.key?(:'volume')
        self.volume = attributes[:'volume']
      end

      if attributes.key?(:'volume_effect')
        self.volume_effect = attributes[:'volume_effect']
      end

      if attributes.key?(:'speed')
        self.speed = attributes[:'speed']
      end

      if attributes.key?(:'crop')
        self.crop = attributes[:'crop']
      end

      if attributes.key?(:'chroma_key')
        self.chroma_key = attributes[:'chroma_key']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @type.nil?
        invalid_properties.push('invalid value for "type", type cannot be nil.')
      end

      if !@src.nil? && @src.to_s.length < 1
        invalid_properties.push('invalid value for "src", the character length must be great than or equal to 1.')
      end

      pattern = Regexp.new(/\S/)
      if !@src.nil? && @src !~ pattern
        invalid_properties.push("invalid value for \"src\", must conform to the pattern #{pattern}.")
      end

      if !@prompt.nil? && @prompt.to_s.length > 4000
        invalid_properties.push('invalid value for "prompt", the character length must be smaller than or equal to 4000.')
      end

      if !@input_src.nil? && @input_src.to_s.length < 1
        invalid_properties.push('invalid value for "input_src", the character length must be great than or equal to 1.')
      end

      if !@seed.nil? && @seed.to_s.length < 1
        invalid_properties.push('invalid value for "seed", the character length must be great than or equal to 1.')
      end

      if !@speed.nil? && @speed > 10
        invalid_properties.push('invalid value for "speed", must be smaller than or equal to 10.')
      end

      if !@speed.nil? && @speed < 0
        invalid_properties.push('invalid value for "speed", must be greater than or equal to 0.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @type.nil?
      type_validator = EnumAttributeValidator.new('String', ["video"])
      return false unless type_validator.valid?(@type)
      return false if !@src.nil? && @src.to_s.length < 1
      return false if !@src.nil? && @src !~ Regexp.new(/\S/)
      return false if !@prompt.nil? && @prompt.to_s.length > 4000
      return false if !@input_src.nil? && @input_src.to_s.length < 1
      return false if !@seed.nil? && @seed.to_s.length < 1
      volume_effect_validator = EnumAttributeValidator.new('String', ["none", "fadeIn", "fadeOut", "fadeInFadeOut"])
      return false unless volume_effect_validator.valid?(@volume_effect)
      return false if !@speed.nil? && @speed > 10
      return false if !@speed.nil? && @speed < 0
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] type Object to be assigned
    def type=(type)
      validator = EnumAttributeValidator.new('String', ["video"])
      unless validator.valid?(type)
        fail ArgumentError, "invalid value for \"type\", must be one of #{validator.allowable_values}."
      end
      @type = type
    end

    # Custom attribute writer method with validation
    # @param [Object] src Value to be assigned
    def src=(src)
      if src.nil?
        fail ArgumentError, 'src cannot be nil'
      end

      if src.to_s.length < 1
        fail ArgumentError, 'invalid value for "src", the character length must be great than or equal to 1.'
      end

      pattern = Regexp.new(/\S/)
      if src !~ pattern
        fail ArgumentError, "invalid value for \"src\", must conform to the pattern #{pattern}."
      end

      @src = src
    end

    # Custom attribute writer method with validation
    # @param [Object] prompt Value to be assigned
    def prompt=(prompt)
      if prompt.nil?
        fail ArgumentError, 'prompt cannot be nil'
      end

      if prompt.to_s.length > 4000
        fail ArgumentError, 'invalid value for "prompt", the character length must be smaller than or equal to 4000.'
      end

      @prompt = prompt
    end

    # Custom attribute writer method with validation
    # @param [Object] input_src Value to be assigned
    def input_src=(input_src)
      if input_src.nil?
        fail ArgumentError, 'input_src cannot be nil'
      end

      if input_src.to_s.length < 1
        fail ArgumentError, 'invalid value for "input_src", the character length must be great than or equal to 1.'
      end

      @input_src = input_src
    end

    # Custom attribute writer method with validation
    # @param [Object] seed Value to be assigned
    def seed=(seed)
      if seed.nil?
        fail ArgumentError, 'seed cannot be nil'
      end

      if seed.to_s.length < 1
        fail ArgumentError, 'invalid value for "seed", the character length must be great than or equal to 1.'
      end

      @seed = seed
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] volume_effect Object to be assigned
    def volume_effect=(volume_effect)
      validator = EnumAttributeValidator.new('String', ["none", "fadeIn", "fadeOut", "fadeInFadeOut"])
      unless validator.valid?(volume_effect)
        fail ArgumentError, "invalid value for \"volume_effect\", must be one of #{validator.allowable_values}."
      end
      @volume_effect = volume_effect
    end

    # Custom attribute writer method with validation
    # @param [Object] speed Value to be assigned
    def speed=(speed)
      if speed.nil?
        fail ArgumentError, 'speed cannot be nil'
      end

      if speed > 10
        fail ArgumentError, 'invalid value for "speed", must be smaller than or equal to 10.'
      end

      if speed < 0
        fail ArgumentError, 'invalid value for "speed", must be greater than or equal to 0.'
      end

      @speed = speed
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          type == o.type &&
          src == o.src &&
          prompt == o.prompt &&
          input_src == o.input_src &&
          seed == o.seed &&
          model == o.model &&
          transcode == o.transcode &&
          trim == o.trim &&
          volume == o.volume &&
          volume_effect == o.volume_effect &&
          speed == o.speed &&
          crop == o.crop &&
          chroma_key == o.chroma_key
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [type, src, prompt, input_src, seed, model, transcode, trim, volume, volume_effect, speed, crop, chroma_key].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Shotstack.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
