=begin
#Shotstack

# Official Ruby SDK for the Shotstack Cloud Video Editing API

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.4.0

=end

require 'date'
require 'time'

module Shotstack
  # Options to control the visibility of videos and privacy features.
  class VimeoDestinationPrivacyOptions
    # Set who can view the videos. Available options are: <ul>   <li>`anybody` - Anyone can view the video.</li>   <li>`nobody` - Only the video owner can view the video.</li>   <li>`contacts` - Only contacts can view the video.</li>   <li>`password` - A password is required to view the video.</li>   <li>`unlisted` - The video is not listed on Vimeo.</li> </ul>
    attr_accessor :view

    # Set who can embed the video. Available options are: <ul>   <li>`public` - Anyone can embed the video.</li>   <li>`private` - Only the video owner can embed the video.</li>   <li>`whitelist` - Only whitelisted domains can embed the video.</li> </ul>
    attr_accessor :embed

    # Set who can comment on the video. Available options are: <ul>   <li>`anybody` - Anyone can comment on the video.</li>   <li>`nobody` - Only the video owner can comment on the video.</li>   <li>`contacts` - Only contacts can comment on the video.</li> </ul>
    attr_accessor :comments

    # Set whether the video can be downloaded.
    attr_accessor :download

    # Set whether other users can add the video to their collections.
    attr_accessor :add

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'view' => :'view',
        :'embed' => :'embed',
        :'comments' => :'comments',
        :'download' => :'download',
        :'add' => :'add'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'view' => :'String',
        :'embed' => :'String',
        :'comments' => :'String',
        :'download' => :'Boolean',
        :'add' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Shotstack::VimeoDestinationPrivacyOptions` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Shotstack::VimeoDestinationPrivacyOptions`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'view')
        self.view = attributes[:'view']
      end

      if attributes.key?(:'embed')
        self.embed = attributes[:'embed']
      end

      if attributes.key?(:'comments')
        self.comments = attributes[:'comments']
      end

      if attributes.key?(:'download')
        self.download = attributes[:'download']
      end

      if attributes.key?(:'add')
        self.add = attributes[:'add']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      view_validator = EnumAttributeValidator.new('String', ["anybody", "nobody", "contacts", "password", "unlisted"])
      return false unless view_validator.valid?(@view)
      embed_validator = EnumAttributeValidator.new('String', ["public", "private", "whitelist"])
      return false unless embed_validator.valid?(@embed)
      comments_validator = EnumAttributeValidator.new('String', ["anybody", "nobody", "contacts"])
      return false unless comments_validator.valid?(@comments)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] view Object to be assigned
    def view=(view)
      validator = EnumAttributeValidator.new('String', ["anybody", "nobody", "contacts", "password", "unlisted"])
      unless validator.valid?(view)
        fail ArgumentError, "invalid value for \"view\", must be one of #{validator.allowable_values}."
      end
      @view = view
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] embed Object to be assigned
    def embed=(embed)
      validator = EnumAttributeValidator.new('String', ["public", "private", "whitelist"])
      unless validator.valid?(embed)
        fail ArgumentError, "invalid value for \"embed\", must be one of #{validator.allowable_values}."
      end
      @embed = embed
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] comments Object to be assigned
    def comments=(comments)
      validator = EnumAttributeValidator.new('String', ["anybody", "nobody", "contacts"])
      unless validator.valid?(comments)
        fail ArgumentError, "invalid value for \"comments\", must be one of #{validator.allowable_values}."
      end
      @comments = comments
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          view == o.view &&
          embed == o.embed &&
          comments == o.comments &&
          download == o.download &&
          add == o.add
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [view, embed, comments, download, add].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Shotstack.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
